#!/bin/bash

echo "==============================================================="
echo -e "#       \033[31m\033[1m\033[5m     Prohibition of non-authorised use\033[0m                #"
echo "==============================================================="
echo "System Information:"
echo -e "Hostname: '\033[33m\033[1m$(hostname)\033[0m'"
echo "Uptime: $(uptime | awk '{print $3,$4}' | sed 's/,//')"
echo "Memory Usage: $(free | awk '/Mem/{printf("%.2f%"), $3/$2*100}')"
echo "Disk Usage: $(df -h / | awk '/\//{print $(NF-1)}')"
echo "==============================================================="
