#!/bin/sh

# CPU 정보 수집
CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')

# 메모리 정보 수집
MEM_TOTAL=$(free -m | grep Mem | awk '{print $2}')
MEM_USED=$(free -m | grep Mem | awk '{print $3}')
MEM_USAGE=$((100 * $MEM_USED / $MEM_TOTAL))

# 디스크 사용량 정보 수집
DISK_USAGE=$(df -h / | tail -n 1 | awk '{print $5}')

# motd 파일에 리소스 정보 추가
echo "CPU 사용량: $CPU_USAGE%" > /etc/motd
echo "메모리 사용량: $MEM_USAGE%" >> /etc/motd
echo "디스크 사용량: $DISK_USAGE" >> /etc/motd

sudo chmod +x /etc/update-motd.d/99-custom-motd

sudo update-motd
